export const controls = [
  {
    name: 'variant',
    label: 'Variant',
    type: 'select',
    value: 'default',
    options: [
      'default',
      'active',
      'base',
      'primary',
      'info',
      'danger',
      'warning',
      'success',
      'indigo',
      'purple',
      'pink',
      'recommanded',
      'outline',
    ],
  },
  {
    name: 'size',
    label: 'Size',
    type: 'select',
    value: 'sm',
    options: ['sm', 'md', 'lg', 'badge'],
  },
  {
    name: 'pill',
    label: 'Pill Style',
    type: 'boolean',
    value: false,
  },
  {
    name: 'label',
    label: 'Label Text',
    type: 'text',
    value: 'New',
  },
  {
    name: 'icon',
    label: 'Icon ID',
    type: 'text',
    value: 'check',
  },
  {
    name: 'href',
    label: 'Href (leave empty for span)',
    type: 'text',
    value: '',
  },
  {
    name: 'className',
    label: 'Extra CSS Classes',
    type: 'text',
    value: '',
  },
];
