import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ButtonComponent,
  BadgeComponent,
  IconComponent,
  AccordionComponent,
  AvatarComponent,
  DsTabsComponent,
  DsContainerComponent,
  DsHeadingComponent,
  DsTextComponent,
  DsActionsLayoutComponent,
  DsBreadcrumbComponent,
  CallToActionIconsComponent,
  EmptyCardComponent,
  DsPortfolioItemComponent,
  DsPortfolioSelectionComponent,
  DsToggleComponent,
  DsShortcutCardComponent,
} from './components';

import { DesignSystemComponent } from './design-system.component';

@NgModule({
  declarations: [
    DesignSystemComponent,
    ButtonComponent,
    BadgeComponent,
    IconComponent,
    AccordionComponent,
    AvatarComponent,
    DsTabsComponent,
    DsContainerComponent,
    DsHeadingComponent,
    DsTextComponent,
    DsActionsLayoutComponent,
    DsBreadcrumbComponent,
    CallToActionIconsComponent,
    EmptyCardComponent,
    DsPortfolioItemComponent,
    DsPortfolioSelectionComponent,
    DsToggleComponent,
    DsShortcutCardComponent,
  ],
  imports: [CommonModule],
  exports: [
    DesignSystemComponent,
    ButtonComponent,
    BadgeComponent,
    IconComponent,
    AccordionComponent,
    AvatarComponent,
    DsTabsComponent,
    DsContainerComponent,
    DsHeadingComponent,
    DsTextComponent,
    DsActionsLayoutComponent,
    DsBreadcrumbComponent,
    CallToActionIconsComponent,
    EmptyCardComponent,
    DsPortfolioItemComponent,
    DsPortfolioSelectionComponent,
    DsToggleComponent,
    DsShortcutCardComponent,
  ],
})
export class DesignSystemModule {}
